robot_localization:
  ros__parameters:
    use_sim_time: true
    frequency: 30.0
    two_d_mode: true

    base_link_frame: base_link
    odom_frame: odom
    world_frame: odom
    publish_tf: true

    odom0: /odometry
    odom0_config: [true, true, false,   # x y z
                   false, false, true,  # roll pitch yaw
                   true, true, false,   # vx vy vz
                   false, false, true,  # vroll vpitch vyaw
                   false, false, false] # ax ay az
    odom0_differential: false

    imu0: /imu
    imu0_remove_gravitational_acceleration: true
    imu0_config: [false, false, false,
                  true,  true,  true,   # orientation
                  false, false, false,
                  false, false, true,   # yaw rate
                  true,  true,  true]   # linear acc
