<?xml version="1.0" ?>
<robot name="parrot" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find 41068_ignition_bringup)/urdf_drone/common_properties.urdf.xacro"/>
  <xacro:include filename="$(find 41068_ignition_bringup)/urdf_drone/parrot.gazebo.xacro"/>

  <xacro:property name="r200_cam_rgb_px" value="0.005"/>
  <xacro:property name="r200_cam_rgb_py" value="0.018"/>
  <xacro:property name="r200_cam_rgb_pz" value="0.013"/>
  <xacro:property name="r200_cam_depth_offset" value="0.01"/>


  <!-- Main link -->
  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.503"/> <!-- kg -->
      <inertia ixx="1.805e-3" ixy="-8.619e-7" ixz="1.555e-5"
               iyy="1.764e-3" iyz="3.595e-7"
               izz="3.328e-3" />
    </inertial>
<!--     <collision name="collision">
      <origin xyz="-0.00424 0.00014 -0.00595" rpy="0 0 0"/>
      <geometry>
        <box size="0.5 0.5 0.2"/>
      </geometry>
    </collision> -->
    <visual name="hull">
      <geometry>
        <mesh filename="file://$(find 41068_ignition_bringup)/urdf_drone/meshes/hull.dae"/>
      </geometry>
    </visual>
    <visual name="propeller_rr">
      <origin xyz="-0.09035 -0.11423 -0.00501" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find 41068_ignition_bringup)/urdf_drone/meshes/propeller_rr.dae"/>
      </geometry>
    </visual>
    <visual name="propeller_rl">
      <origin xyz="0.09035 0.11452 -0.00501" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find 41068_ignition_bringup)/urdf_drone/meshes/propeller_rl.dae"/>
      </geometry>
    </visual>
    <visual name="propeller_fr">
      <origin xyz="0.08456 -0.11435 -0.00501" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find 41068_ignition_bringup)/urdf_drone/meshes/propeller_fr.dae"/>
      </geometry>
    </visual>
    <visual name="propeller_fl">
      <origin xyz="0.08456 0.11463 -0.00501" rpy="0 0 0"/>
      <geometry>
        <mesh filename="file://$(find 41068_ignition_bringup)/urdf_drone/meshes/propeller_fl.dae"/>
      </geometry>
    </visual>
  </link>


  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0.0 0 0.068" rpy="0 0 0"/>
  </joint>

  <link name="imu_link"/>

  <joint name="scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="0 0 0.2" rpy="0 0 0"/>
  </joint>

  <link name="base_scan">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.04" radius="0.09"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <inertial>
      <mass value="0" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <origin xyz="0.25 0.0 0.25" rpy="0 0.785398 0"/> <!-- 0.5 0.0 0.9 -->
    <parent link="base_link"/>
    <child link="camera_link"/>
  </joint>

  <link name="camera_link">
    <visual>
     <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.08 0.05"/>
      </geometry>
      <material name="dark"/>
    </visual>
    <visual>
     <origin xyz="0.015 0 0" rpy="0 1.57 0"/>
      <geometry>
        <cylinder length="0.03" radius="0.02"/>
      </geometry>
      <material name="dark"/>
    </visual>
  </link>

  <joint name="camera_rgb_joint" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_rgb_frame"/>
  </joint>
  <link name="camera_rgb_frame"/>

  <joint name="camera_rgb_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_rgb_frame"/>
    <child link="camera_rgb_optical_frame"/>
  </joint>
  <link name="camera_rgb_optical_frame"/>

  <joint name="camera_depth_joint" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py + r200_cam_depth_offset} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_depth_frame"/>
  </joint>
  <link name="camera_depth_frame"/>

  <joint name="camera_depth_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_depth_frame"/>
    <child link="camera_depth_optical_frame"/>
  </joint>
  <link name="camera_depth_optical_frame"/>

</robot>
