<?xml version="1.0"?>
<package format="3">
  <name>thermal_detection</name>
  <version>0.0.1</version>
  <description>Parrot quadcopter with RGB + thermal sensors in Gazebo (Ignition).</description>

  <maintainer email="student@example.com">student</maintainer>
  <license>Apache-2.0</license>

  <!-- Build system -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- ROS message deps used at runtime -->
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>

  <!-- Python client lib (your detector node) -->
  <exec_depend>rclpy</exec_depend>

  <!-- Runtime tools used by launches -->
  <exec_depend>xacro</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <!-- Optional: if your detector uses NumPy/OpenCV, add these -->
  <!-- <exec_depend>python3-numpy</exec_depend> -->
  <!-- <exec_depend>cv_bridge</exec_depend> -->
  <!-- <exec_depend>image_transport</exec_depend> -->

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

